### ISSUE TITLE
plymouth.hook fails causing initramfs-tools to stop working 

### ISSUE THREAD

**Issue by vontycowicz** [pop-os/plymouth#2]
Hi,

not sure this is the right place to post this issue but it seams that the plymouth version `0.9.5git20210406-0ubuntu2pop0~1646146081~18.04~23915e9` delivered with the recent updates on pop-os 18.04 breaks initramfs-tools preventing successful preparation of kernel images.
Note that there is also an ongoing discussion on [utuntu forums](https://ubuntuforums.org/showthread.php?t=2472551) about this behavior.

**Comment by 13r0ck** [comment]
The version for 18.04 was rolled back. This should no longer be an issue
