### ISSUE TITLE
[HP Omen / L66157-001 OLED panel] Entry field does not scale 

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/plymouth#6]
Currently the entry field for the passphrase does not scale for HiDPI. It looks like you can do this though it would need to be done for each device as it is put into the initrd:

https://wiki.archlinux.org/title/plymouth#Hidpi

Photo of issue on a 4K (3840x2160) 15" screen:

![PXL_20220822_225111812](https://user-images.githubusercontent.com/4884946/188636649-36a3bb63-7c58-40a7-8064-a2a65fcd9f44.jpg)

**Comment by ahoneybun** [comment]
Looks like that file doesn't exist in Ubuntu and it may not work any longer: https://gitlab.freedesktop.org/plymouth/plymouth/-/issues/115

From what I can find it looks like GRUB was used to adjust this before:

https://askubuntu.com/questions/503766/change-plymouth-screen-resolution

**Comment by jacobgkau** [comment]
I thought https://github.com/pop-os/plymouth-theme/pull/25 / https://github.com/pop-os/plymouth-theme/pull/28 fixed this quite a while ago. The prompt seems to be scaled on an addw2 (15.6" 4k).

![P1060840](https://user-images.githubusercontent.com/7199422/188713982-b920d73e-7736-4532-a081-5c9edfbaa8e3.jpg)

**Comment by ahoneybun** [comment]
That's not how it looks for me on non-System76 hardware. Maybe there is something in the system76-driver.

**Comment by jacobgkau** [comment]
What hardware is pictured in your description, specifically? Laptop model & LCD panel model?

**Comment by ahoneybun** [comment]
Looks like it is made by HP as L66157-001 though I can't seem to find much information about it online other then it is 4K OLED.

**Comment by ahoneybun** [comment]
It looks like either the kernel update or some update corrected the issue so my screen looks like the addw2 so I'm closing this issue.
